# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GiftWrap
                                 A QGIS plugin
 This plugin prepares the contents of a map for sharing by copying all data into
 a local directory and saving a copy of the map.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-03-05
        copyright            : (C) 2020 by Toole Design
        email                : sgardner@tooledesign.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GiftWrap class from file GiftWrap.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gift_wrap import GiftWrap
    return GiftWrap(iface)
